#!/bin/bash

IMAGE_NAME=dev-pdw
CONTAINER_NAME=dev-pdw
CONTAINER_IP_ADDRESS=172.18.0.30
MONGO_BIGCHAINDB_CONTAINER_NAME=${CONTAINER_NAME}-mongo-bigchaindb
MONGO_BIGCHAINDB_CONTAINER_IP_ADDRESS=172.18.0.31
